"""Scaffold emitters: dbt sources/staging and Snowflake landing DDL from a profile.

Everything emitted derives from profile facts — masks, rates, alerts — never
from values, so generated artifacts inherit the safety contract. One
deliberate consequence: `accepted_values` tests are NOT generated (the
profile knows a column has 3 distinct codes, not what they are); a TODO
marks where a human supplies the code list.

Design note: the winning move in the core-bet experiment was stats-grounded
output (null rates in descriptions, footer-recovery warnings, alert-driven
casts). Schema-only interchange formats can't carry that, which is why these
emitters read profile.json natively rather than exporting ODCS.
"""

from __future__ import annotations

import re
from typing import Any


def snake(name: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"[^0-9a-zA-Z]+", "_", s).strip("_").lower()
    # Merged group headers can double a token ("Claim Claim ID"): collapse
    # adjacent duplicates.
    tokens = []
    for token in s.split("_"):
        if not tokens or tokens[-1] != token:
            tokens.append(token)
    s = "_".join(tokens)
    return f"col_{s}" if not s or s[0].isdigit() else s


def table_key(table: dict[str, Any]) -> str:
    return snake(table["name"].rsplit("/", 1)[-1])


def _lands_as_text(col: dict[str, Any]) -> bool:
    """Columns that came from text or whose numeric form is a lie land as
    VARCHAR for fidelity; staging casts them."""
    if col.get("type_recovered"):
        return True
    alerts = col.get("alerts", [])
    if "possible_leading_zero_loss" in alerts:
        return True
    base = col["physical_type"].split("(")[0].upper()
    return base != "VARCHAR" and bool(col.get("masks")) and base in (
        "TINYINT", "SMALLINT", "INTEGER", "BIGINT", "HUGEINT"
    )


def _sf_type(col: dict[str, Any]) -> str:
    if _lands_as_text(col):
        return "VARCHAR"
    base = col["physical_type"].split("(")[0].upper()
    mapping = {
        "TINYINT": "NUMBER(38,0)", "SMALLINT": "NUMBER(38,0)", "INTEGER": "NUMBER(38,0)",
        "BIGINT": "NUMBER(38,0)", "HUGEINT": "NUMBER(38,0)",
        "DOUBLE": "FLOAT", "FLOAT": "FLOAT",
        "DATE": "DATE", "TIMESTAMP": "TIMESTAMP_NTZ", "BOOLEAN": "BOOLEAN",
    }
    if base == "DECIMAL" and col.get("numeric", {}).get("precision_scale"):
        return f"NUMBER({col['numeric']['precision_scale']})"
    return mapping.get(base, "VARCHAR")


def describe(col: dict[str, Any]) -> str:
    """A stats-grounded, value-free column description."""
    parts: list[str] = []
    semantic = col.get("semantic") or []
    if semantic:
        top = semantic[0]
        rate = f" ({top['match_rate']:.0%})" if top.get("match_rate") is not None else " (name+shape)"
        parts.append(f"{top['type']}{rate}")
    if col.get("constant"):
        parts.append("constant in profiled data")
    if col.get("masks"):
        parts.append(f"shape {col['masks'][0]['mask']}")
    nulls = col.get("nulls", {}).get("rate")
    if nulls is not None:
        parts.append("no nulls" if nulls == 0 else f"{nulls:.1%} null")
    if col.get("uniqueness_ratio") == 1.0:
        parts.append("unique")
    elif col.get("distinct") is not None:
        parts.append(f"{col['distinct']} distinct")
    if col.get("type_recovered"):
        rec = col["type_recovered"]
        parts.append(f"text-origin, casts to {rec['to']} at {rec['confidence']:.0%}")
    for alert in col.get("alerts", []):
        if alert.startswith("sensitive_"):
            parts.append(f"SENSITIVE ({alert.removeprefix('sensitive_')}) — masking-policy candidate")
        elif alert == "possible_leading_zero_loss":
            parts.append("leading zeros lost upstream; re-pad in staging")
        elif alert == "mixed_casing":
            parts.append("mixed casing; normalize before grouping")
        elif alert == "near_unique":
            parts.append("NEAR-unique (data-quality flag)")
    return "; ".join(parts) or "no profile facts"


def _tables(profile: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        t
        for t in profile.get("tables", [])
        if not t.get("not_tabular") and not t.get("suppressed_small_table")
    ]


def emit_snowflake(profile: dict[str, Any], database: str = "RAW", schema: str = "VENDOR") -> str:
    lines = [
        "-- Generated by silueta emit snowflake. Derived from profile facts only — no data values.",
        f"CREATE SCHEMA IF NOT EXISTS {database}.{schema};",
        "",
    ]
    for table in _tables(profile):
        tname = table_key(table).upper()
        lines.append(f"CREATE OR REPLACE TABLE {database}.{schema}.{tname} (")
        col_lines = []
        for col in table["columns"]:
            comment = describe(col).replace("'", "''")
            col_lines.append(f"    {snake(col['name']).upper():<24}{_sf_type(col):<16}COMMENT '{comment}'")
        lines.append(",\n".join(col_lines))
        recovery = table.get("recovery", {})
        note = f" -- profiler recovery: {recovery}" if recovery else ""
        lines.append(f"); -- {table['rows']:,} rows profiled{note}")
        if recovery.get("dropped_footer_rows"):
            lines.append(
                f"-- WARNING: source sheet has {recovery['dropped_footer_rows']} trailing footer row(s) "
                "(e.g. totals). Exclude them in the loader or they will corrupt casts."
            )
        lines.append("")
    return "\n".join(lines)


def emit_dbt_sources(profile: dict[str, Any], source_name: str = "vendor") -> str:
    relations = profile.get("relations", [])
    rel_by_from = {(r["from_table"], r["from_column"]): r for r in relations}
    table_by_name = {t["name"]: t for t in _tables(profile)}

    out = [
        "# Generated by silueta emit dbt. Descriptions and tests derive from profile facts only.",
        "version: 2",
        "",
        "sources:",
        f"  - name: {source_name}",
        "    tables:",
    ]
    for table in _tables(profile):
        out.append(f"      - name: {table_key(table)}")
        desc = f"{table['rows']:,} rows profiled from {table['source']}"
        if table.get("recovery"):
            desc += f"; recovery: {table['recovery']}"
        out.append(f'        description: "{desc}"')
        out.append("        columns:")
        for col in table["columns"]:
            out.append(f"          - name: {snake(col['name'])}")
            out.append(f'            description: "{describe(col)}"')
            tests: list[str] = []
            if col.get("uniqueness_ratio") == 1.0:
                tests.append("unique")
            if col.get("nulls", {}).get("rate") == 0:
                tests.append("not_null")
            rel = rel_by_from.get((table["name"], col["name"]))
            data_tests = [f"              - {t}" for t in tests]
            if rel and rel["to_table"] in table_by_name:
                to_table = table_key(table_by_name[rel["to_table"]])
                to_col = snake(rel["to_column"])
                data_tests.append("              - relationships:")
                data_tests.append(f"                  to: source('{source_name}', '{to_table}')")
                data_tests.append(f"                  field: {to_col}")
            if data_tests:
                out.append("            data_tests:")
                out.extend(data_tests)
            distinct = col.get("distinct")
            if distinct is not None and distinct <= 10 and col.get("uniqueness_ratio", 1) < 0.5:
                out.append(
                    f"            # TODO accepted_values: column has {distinct} distinct codes; "
                    "silueta never emits values — supply the code list."
                )
        out.append("")
    return "\n".join(out)


def _staging_expr(col: dict[str, Any]) -> str:
    raw = snake(col["name"]).upper()
    expr = raw
    alerts = col.get("alerts", [])
    recovered = (col.get("type_recovered") or {}).get("to")
    semantic_types = {s["type"] for s in col.get("semantic") or []}

    if "possible_leading_zero_loss" in alerts and "us_zip" in col.get("name_signals", []):
        expr = f"LPAD({expr}, 5, '0')"
    elif recovered in ("DOUBLE", "BIGINT"):
        expr = f"TRY_CAST(REPLACE({expr}, ',', '') AS NUMBER(18,2))"
    elif recovered in ("DATE", "TIMESTAMP") or "us_date" in semantic_types:
        expr = (
            f"TRY_TO_DATE({expr}, 'MM/DD/YYYY')" if "us_date" in semantic_types else f"TRY_CAST({expr} AS DATE)"
        )
    elif _lands_as_text(col):
        expr = f"TRIM({expr})"
    if "mixed_casing" in alerts:
        expr = f"UPPER({expr})"
    return expr


def emit_dbt_staging(table: dict[str, Any], source_name: str = "vendor") -> str:
    tkey = table_key(table)
    lines = [
        f"-- stg_{tkey}: generated by silueta emit dbt from profile facts only.",
    ]
    recovery = table.get("recovery", {})
    if recovery:
        lines.append(f"-- profiler recovery on source sheet: {recovery}")
    lines += [
        "",
        "with source as (",
        f"    select * from {{{{ source('{source_name}', '{tkey}') }}}}",
        "),",
        "",
        "renamed as (",
        "    select",
    ]
    cols = []
    for col in table["columns"]:
        expr = _staging_expr(col)
        target = snake(col["name"])
        default = f"        {target.upper()} as {target}"
        cols.append(f"        {expr} as {target}" if expr != target.upper() else default)
    lines.append(",\n".join(cols))
    lines += ["    from source", ")", "", "select * from renamed"]
    return "\n".join(lines) + "\n"
